#ifndef OPCODES
#define OPCODES

#define OPCODE_NOP 0x00
#define OPCODE_LXI_B_D16 0x01
#define OPCODE_STAX_B 0x02
#define OPCODE_INX_B 0x03
#define OPCODE_INR_B 0x04
#define OPCODE_DCR_B 0x05
#define OPCODE_MVI_B_D8 0x06
#define OPCODE_RLC 0x07

#define OPCODE_DAD_B 0x09
#define OPCODE_LDAX_B 0x0a
#define OPCODE_DCX_B 0x0b
#define OPCODE_INR_C 0x0c
#define OPCODE_DCR_C 0x0d
#define OPCODE_MVI_C_D8 0x0e
#define OPCODE_RRC 0x0f

#define OPCODE_LXI_D_D16 0x11
#define OPCODE_STAX_D 0x12
#define OPCODE_INX_D 0x13
#define OPCODE_INR_D 0x14
#define OPCODE_DCR_D 0x15
#define OPCODE_MVI_D_D8 0x16
#define OPCODE_RAL 0x17

#define OPCODE_DAD_D 0x19
#define OPCODE_LDAX_D 0x1a
#define OPCODE_DCX_D 0x1b
#define OPCODE_INR_E 0x1c
#define OPCODE_DCR_E 0x1d
#define OPCODE_MVI_E_D8 0x1e
#define OPCODE_RAR 0x1f

#define OPCODE_LXI_H_D16 0x21
#define OPCODE_SHLD 0x22
#define OPCODE_INX_H 0x23
#define OPCODE_INR_H 0x24
#define OPCODE_DCR_H 0x25
#define OPCODE_MVI_H_D8 0x26
#define OPCODE_DAA 0x27

#define OPCODE_DAD_H 0x29
#define OPCODE_LHLD 0x2a
#define OPCODE_DCX_H 0x2b
#define OPCODE_INR_L 0x2c
#define OPCODE_DCR_L 0x2d
#define OPCODE_MVI_L_D8 0x2e
#define OPCODE_CMA 0x2f

#define OPCODE_LXI_SP_D16 0x31
#define OPCODE_STA 0x32
#define OPCODE_INX_SP 0x33
#define OPCODE_INR_M 0x34
#define OPCODE_DCR_M 0x35
#define OPCODE_MVI_M_D8 0x36
#define OPCODE_STC 0x37

#define OPCODE_DAD_SP 0x39
#define OPCODE_LDA 0x3a
#define OPCODE_DCX_SP 0x3b
#define OPCODE_INR_A 0x3c
#define OPCODE_DCR_A 0x3d
#define OPCODE_MVI_A_D8 0x3e
#define OPCODE_CMC 0x3f
#define OPCODE_MOV_B_B 0x40
#define OPCODE_MOV_B_C 0x41
#define OPCODE_MOV_B_D 0x42
#define OPCODE_MOV_B_E 0x43
#define OPCODE_MOV_B_H 0x44
#define OPCODE_MOV_B_L 0x45
#define OPCODE_MOV_B_M 0x46
#define OPCODE_MOV_B_A 0x47
#define OPCODE_MOV_C_B 0x48
#define OPCODE_MOV_C_C 0x49
#define OPCODE_MOV_C_D 0x4a
#define OPCODE_MOV_C_E 0x4b
#define OPCODE_MOV_C_H 0x4c
#define OPCODE_MOV_C_L 0x4d
#define OPCODE_MOV_C_M 0x4e
#define OPCODE_MOV_C_A 0x4f
#define OPCODE_MOV_D_B 0x50
#define OPCODE_MOV_D_C 0x51
#define OPCODE_MOV_D_D 0x52
#define OPCODE_MOV_D_E 0x53
#define OPCODE_MOV_D_H 0x54
#define OPCODE_MOV_D_L 0x55
#define OPCODE_MOV_D_M 0x56
#define OPCODE_MOV_D_A 0x57
#define OPCODE_MOV_E_B 0x58
#define OPCODE_MOV_E_C 0x59
#define OPCODE_MOV_E_D 0x5a
#define OPCODE_MOV_E_E 0x5b
#define OPCODE_MOV_E_H 0x5c
#define OPCODE_MOV_E_L 0x5d
#define OPCODE_MOV_E_M 0x5e
#define OPCODE_MOV_E_A 0x5f
#define OPCODE_MOV_H_B 0x60
#define OPCODE_MOV_H_C 0x61
#define OPCODE_MOV_H_D 0x62
#define OPCODE_MOV_H_E 0x63
#define OPCODE_MOV_H_H 0x64
#define OPCODE_MOV_H_L 0x65
#define OPCODE_MOV_H_M 0x66
#define OPCODE_MOV_H_A 0x67
#define OPCODE_MOV_L_B 0x68
#define OPCODE_MOV_L_C 0x69
#define OPCODE_MOV_L_D 0x6a
#define OPCODE_MOV_L_E 0x6b
#define OPCODE_MOV_L_H 0x6c
#define OPCODE_MOV_L_L 0x6d
#define OPCODE_MOV_L_M 0x6e
#define OPCODE_MOV_L_A 0x6f
#define OPCODE_MOV_M_B 0x70
#define OPCODE_MOV_M_C 0x71
#define OPCODE_MOV_M_D 0x72
#define OPCODE_MOV_M_E 0x73
#define OPCODE_MOV_M_H 0x74
#define OPCODE_MOV_M_L 0x75
#define OPCODE_HLT 0x76
#define OPCODE_MOV_M_A 0x77
#define OPCODE_MOV_A_B 0x78
#define OPCODE_MOV_A_C 0x79
#define OPCODE_MOV_A_D 0x7a
#define OPCODE_MOV_A_E 0x7b
#define OPCODE_MOV_A_H 0x7c
#define OPCODE_MOV_A_L 0x7d
#define OPCODE_MOV_A_M 0x7e
#define OPCODE_MOV_A_A 0x7f
#define OPCODE_ADD_B 0x80
#define OPCODE_ADD_C 0x81
#define OPCODE_ADD_D 0x82
#define OPCODE_ADD_E 0x83
#define OPCODE_ADD_H 0x84
#define OPCODE_ADD_L 0x85
#define OPCODE_ADD_M 0x86
#define OPCODE_ADD_A 0x87
#define OPCODE_ADC_B 0x88
#define OPCODE_ADC_C 0x89
#define OPCODE_ADC_D 0x8a
#define OPCODE_ADC_E 0x8b
#define OPCODE_ADC_H 0x8c
#define OPCODE_ADC_L 0x8d
#define OPCODE_ADC_M 0x8e
#define OPCODE_ADC_A 0x8f
#define OPCODE_SUB_B 0x90
#define OPCODE_SUB_C 0x91
#define OPCODE_SUB_D 0x92
#define OPCODE_SUB_E 0x93
#define OPCODE_SUB_H 0x94
#define OPCODE_SUB_L 0x95
#define OPCODE_SUB_M 0x96
#define OPCODE_SUB_A 0x97
#define OPCODE_SBB_B 0x98
#define OPCODE_SBB_C 0x99
#define OPCODE_SBB_D 0x9a
#define OPCODE_SBB_E 0x9b
#define OPCODE_SBB_H 0x9c
#define OPCODE_SBB_L 0x9d
#define OPCODE_SBB_M 0x9e
#define OPCODE_SBB_A 0x9f
#define OPCODE_ANA_B 0xa0
#define OPCODE_ANA_C 0xa1
#define OPCODE_ANA_D 0xa2
#define OPCODE_ANA_E 0xa3
#define OPCODE_ANA_H 0xa4
#define OPCODE_ANA_L 0xa5
#define OPCODE_ANA_M 0xa6
#define OPCODE_ANA_A 0xa7
#define OPCODE_XRA_B 0xa8
#define OPCODE_XRA_C 0xa9
#define OPCODE_XRA_D 0xaa
#define OPCODE_XRA_E 0xab
#define OPCODE_XRA_H 0xac
#define OPCODE_XRA_L 0xad
#define OPCODE_XRA_M 0xae
#define OPCODE_XRA_A 0xaf
#define OPCODE_ORA_B 0xb0
#define OPCODE_ORA_C 0xb1
#define OPCODE_ORA_D 0xb2
#define OPCODE_ORA_E 0xb3
#define OPCODE_ORA_H 0xb4
#define OPCODE_ORA_L 0xb5
#define OPCODE_ORA_M 0xb6
#define OPCODE_ORA_A 0xb7
#define OPCODE_CMP_B 0xb8
#define OPCODE_CMP_C 0xb9
#define OPCODE_CMP_D 0xba
#define OPCODE_CMP_E 0xbb
#define OPCODE_CMP_H 0xbc
#define OPCODE_CMP_L 0xbd
#define OPCODE_CMP_M 0xbe
#define OPCODE_CMP_A 0xbf
#define OPCODE_RNZ 0xc0
#define OPCODE_POP_B 0xc1
#define OPCODE_JNZ 0xc2
#define OPCODE_JMP 0xc3
#define OPCODE_CNZ 0xc4
#define OPCODE_PUSH_B 0xc5
#define OPCODE_ADI_D8 0xc6
#define OPCODE_RST_0 0xc7
#define OPCODE_RZ 0xc8
#define OPCODE_RET 0xc9
#define OPCODE_JZ 0xca

#define OPCODE_CZ 0xcc
#define OPCODE_CALL 0xcd
#define OPCODE_ACI_D8 0xce
#define OPCODE_RST_1 0xcf
#define OPCODE_RNC 0xd0
#define OPCODE_POP_D 0xd1
#define OPCODE_JNC 0xd2
#define OPCODE_OUT_D8 0xd3
#define OPCODE_CNC 0xd4
#define OPCODE_PUSH_D 0xd5
#define OPCODE_SUI_D8 0xd6
#define OPCODE_RST_2 0xd7
#define OPCODE_RC 0xd8

#define OPCODE_JC 0xda
#define OPCODE_IN_D8 0xdb
#define OPCODE_CC 0xdc

#define OPCODE_SBI_D8 0xde
#define OPCODE_RST_3 0xdf
#define OPCODE_RPO 0xe0
#define OPCODE_POP_H 0xe1
#define OPCODE_JPO 0xe2
#define OPCODE_XTHL 0xe3
#define OPCODE_CPO 0xe4
#define OPCODE_PUSH_H 0xe5
#define OPCODE_ANI_D8 0xe6
#define OPCODE_RST_4 0xe7
#define OPCODE_RPE 0xe8
#define OPCODE_PCHL 0xe9
#define OPCODE_JPE 0xea
#define OPCODE_XCHG 0xeb
#define OPCODE_CPE 0xec

#define OPCODE_XRI_D8 0xee
#define OPCODE_RST_5 0xef
#define OPCODE_RP 0xf0
#define OPCODE_POP_PSW 0xf1
#define OPCODE_JP 0xf2
#define OPCODE_DI 0xf3
#define OPCODE_CP 0xf4
#define OPCODE_PUSH_PSW 0xf5
#define OPCODE_ORI_D8 0xf6
#define OPCODE_RST_6 0xf7
#define OPCODE_RM 0xf8
#define OPCODE_SPHL 0xf9
#define OPCODE_JM 0xfa
#define OPCODE_EI 0xfb
#define OPCODE_CM 0xfc

#define OPCODE_CPI_D8 0xfe
#define OPCODE_RST_7 0xff

#endif
